apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumescalers.zghanem.aws
spec:
  group: zghanem.aws
  names:
    kind: VolumeScaler
    listKind: VolumeScalerList
    plural: volumescalers
    singular: volumescaler
    shortNames:
      - vs
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - pvcName
                - threshold
                - scale
                - maxSize
              properties:
                pvcName:
                  type: string
                  description: Name of the PersistentVolumeClaim to monitor.
                threshold:
                  type: string
                  pattern: "^[0-9]+%$"
                  description: Disk usage threshold (e.g., "80%").
                scale:
                  type: string
                  pattern: "^[0-9]+%$"
                  description: Percentage increase to PVC size when threshold is exceeded.
                maxSize:
                  type: string
                  pattern: "^[0-9]+Gi$"
                  description: Maximum size the PVC can scale to.
            status:
              type: object
              properties:
                scaledAt:
                  type: string
                  format: date-time
                  description: Timestamp of the last scaling action.
                reachedMaxSize:
                  type: boolean
                  description: Indicates whether the PVC has reached its maximum size.
      additionalPrinterColumns:
        - name: PVC Name
          type: string
          jsonPath: .spec.pvcName
        - name: Threshold
          type: string
          jsonPath: .spec.threshold
        - name: Scale
          type: string
          jsonPath: .spec.scale
        - name: Max Size
          type: string
          jsonPath: .spec.maxSize
        - name: Scaled At
          type: string
          jsonPath: .status.scaledAt
        - name: Reached Max Size
          type: boolean
          jsonPath: .status.reachedMaxSize
      subresources:
        status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-resizer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-resizer-role
rules:
  - apiGroups: [""]  # Core API group
    resources: ["pods", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["zghanem.aws"]  # Custom API group
    resources: ["volumescalers", "volumescalers/status"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvc-resizer-rolebinding
subjects:
  - kind: ServiceAccount
    name: pvc-resizer
    namespace: default
roleRef:
  kind: ClusterRole
  name: pvc-resizer-role
eiifcbfcbtbnferevfbttbbddnjflvkvnvcnhvdnkihl
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: volumescaler-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      app: volumescaler
  template:
    metadata:
      labels:
        app: volumescaler
    spec:
      serviceAccountName: pvc-resizer
      containers:
        - name: pvc-resizer
          image: ahmedghanem/volumescaler:latest
          imagePullPolicy: Always
          # The Go binary should be compiled to run as PID 1 by default
          # If needed, specify command/args if your binary requires them
          env:
            - name: NODE_NAME_ENV
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: kubelet
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
      volumes:
        - name: kubelet
          hostPath:
            path: /var/lib/kubelet
            type: Directory
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      priorityClassName: system-node-critical
