{{- if .Values.crd.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumescalers.zghanem.aws
spec:
  group: zghanem.aws
  names:
    kind: VolumeScaler
    listKind: VolumeScalerList
    plural: volumescalers
    singular: volumescaler
    shortNames:
      - vs
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - pvcName
                - threshold
                - scale
                - maxSize
              properties:
                pvcName:
                  type: string
                  description: Name of the PersistentVolumeClaim to monitor.
                threshold:
                  type: string
                  pattern: "^[0-9]+%$"
                  description: Disk usage threshold (e.g., "80%").
                scale:
                  type: string
                  pattern: "^[0-9]+%$"
                  description: Percentage increase to PVC size when threshold is exceeded.
                maxSize:
                  type: string
                  pattern: "^[0-9]+Gi$"
                  description: Maximum size the PVC can scale to.
            status:
              type: object
              properties:
                scaledAt:
                  type: string
                  format: date-time
                  description: Timestamp of the last scaling action.
                reachedMaxSize:
                  type: boolean
                  description: Indicates whether the PVC has reached its maximum size.
      additionalPrinterColumns:
        - name: PVC Name
          type: string
          jsonPath: .spec.pvcName
        - name: Threshold
          type: string
          jsonPath: .spec.threshold
        - name: Scale
          type: string
          jsonPath: .spec.scale
        - name: Max Size
          type: string
          jsonPath: .spec.maxSize
        - name: Scaled At
          type: string
          jsonPath: .status.scaledAt
        - name: Reached Max Size
          type: boolean
          jsonPath: .status.reachedMaxSize
  subresources:
    status: {}
{{- end }}