name: CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Replace with your AWS region

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.21.0'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.8.0'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name managed2
        shell: bash

      - name: Verify Kubernetes Connection
        run: |
          kubectl get nodes
        shell: bash

      - name: Helm Dependency Update
        run: |
          helm dependency update ./helm/volumescaler

      - name: Helm Upgrade and Install
        run: |
          helm upgrade --install volumescaler ./helm/volumescaler \
            --namespace kube-system \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/volumescaler \
            --set image.tag=${{ github.sha }} \
            --wait

      - name: Verify Deployment
        run: |
          kubectl rollout status daemonset/volumescaler-daemonset -n kube-system
        shell: bash